name: dotnet CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-18.04
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2.1.0
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.4.0
      with:
        dotnet-version: 3.1.102
    - name: Build with dotnet
      run: dotnet build src/Narfu.sln --configuration Release
    - name: Run tests
      run: dotnet test src/Narfu.sln
